[package]
name = "pomodoru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2.0.3"
tui = "0.19"
crossterm = "0.27.0"
